version: '3.8'

services:

  cookbook:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@cookbook-db:5432/cookbook_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@cookbook-db:5432/cookbook_test
    depends_on:
      - cookbook-db

  cookbook-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
